// Auth actions
export const AUTH_ACTION = "AUTH_ACTION";
export const AUTH_ERROR_ACTION = "AUTH_ERROR_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const REQUEST_AUTH_ACTION = "REQUEST_AUTH_ACTION";

// Dasboard actions
export const FETCH_DASHBOARD_ACTION = "FETCH_EVENTS_ACTION";
export const FETCH_SHORTLIST_ACTION = "FETCH_EVENTS_ACTION";
export const DASHBOARD_ERROR_ACTION = "EVENTS_ERROR_ACTION";

// Detail actions
export const FETCH_DETAIL_ACTION = "FETCH_DETAIL_ACTION";
export const TOGGLE_ITEM_ACTION = "TOGGLE_ITEM_ACTION";
export const UPDATE_DETAIL_ACTION = "UPDATE_DETAIL_ACTION";
export const DETAIL_UPDATE_ERROR_ACTION = "DETAIL_UPDATE_ERROR_ACTION";
export const CHANGE_ITEMS_ACTION = "CHANGE_ITEMS_ACTION";
export const DETAIL_ERROR_ACTION = "DETAIL_ERROR_ACTION";



// export const UPDATE_FORM_STATE = "UPDATE_FORM_STATE";